### ISSUE TITLE
hakyll?

### ISSUE THREAD

**Issue by ousia** [fedora-haskell/pandoc#3] opened 2016-02-09 10:09 UTC
@juhp, sorry if this isn’t the right repository to report this issue.

My question is whether it would be possible to have latest hakyll for latest pandoc in copr?

Many thanks for your help.

**Comment by juhp** [comment] 2016-02-10 04:20
Good question - I think eventually yes... the problem is currently the way I build pandoc etc in copr is kind of a binary-build hack (the libraries are not made available).  The next step should be to automate the building of the deps and so package the libraries properly - then it should be possible to build hakyll, etc too.

Have you tried using [stack](http://haskellstack.org)?  That is probably your best bet right now.

**Comment by ousia** [comment] 2016-03-29 18:04
Sorry, but I’m afraid this is a long way to learn. First, I have to learn hakyll myself.

**Comment by juhp** [comment] 2016-03-30 04:53
This may help: https://jaspervdj.be/hakyll/tutorials.html
I have a stack copr too: https://copr.fedoraproject.org/coprs/petersen/stack/

**Comment by juhp** [comment] 2018-07-25 08:32
Going to close this for now

**Closed as completed by juhp** 2018-07-25 08:32 UTC
